//=============================================================================
// gamestrm.inc
//=============================================================================
// included by multiple files, just change this to define more game streams
//=============================================================================
// streamname,default assignment, stream letter, help text

	STREAMENTRY(cactor,     NULL_STREAM, 'a' ,"actor system" )
	STREAMENTRY(cflow,	NULL_STREAM, 'f' ,"game flow" ) 	// main game flow
	STREAMENTRY(clevel,     NULL_STREAM, 'l' ,"Level system" )
	STREAMENTRY(ctool,      NULL_STREAM, 't' ,"tool set code" )
	STREAMENTRY(ccamera,    NULL_STREAM, 'e' ,"camera code" )
	STREAMENTRY(cframeinfo,	NULL_STREAM, 'n' ,"Frame Info" )

//=============================================================================
