//=============================================================================
// libstrm.inc
//=============================================================================
// included by multiple files, just change this to define more library streams
//=============================================================================
// streamname,default assignment, stream letter, help text

	STREAMENTRY(cmovement,     NULL_STREAM, 'M' ,"Movment handers" )

//=============================================================================
