@*=============================================================================
@* makefile.ins: source file for makefile.inc
@*=============================================================================

@define RENDERER_ENTRY(name, poly,polylower,filename,gouraudFlag, textureFlag, prelitFlag) @nLIB_OBJS+= $(LIB_OBJ_DIR)@+filename@+$(OBJ)
@include renderer.s
@undef RENDERER_ENTRY
