#=============================================================================
# GNUmakefile for savegame library
#=============================================================================
# 'make all'		: Builds the savegame library.
# 'make test'		: Builds a test application which exercises the savegame library.
# 'make clean'		: Deletes all of the results of this makefile.
#=============================================================================

LIB_NAME = savegame

include ../../GNUMakefile.env

################################################################################

LIB_OBJS += \
	$(LIB_OBJ_DIR)sgin$(OBJ) \
	$(LIB_OBJ_DIR)sgout$(OBJ) \
	
#	$(LIB_OBJ_DIR)savei$(OBJ) \
#	$(LIB_OBJ_DIR)saveo$(OBJ) \

################################################################################

#include ../GNUMakefile.lib
include ../../GNUMakefile.rul

################################################################################
