#==============================================================================
# wfsource/source/GNUMakefile.test
#==============================================================================

ifndef TEST_PROG
TEST_PROG = $(LIB_NAME)test
endif

ifndef DEBUGGER
DEBUGGER = gdb
endif
.PHONY : reset_target
reset_target : 
ifeq ($(WF_TARGET),psx)
	$(PSX_DIR)/bin/resetps 1
	$(PSX_DIR)/bin/run -w2 $(PSX_DIR)/bin/snpatch
	$(COMSPEC) delay 2^exit
endif

run_test : $(LIB_OBJ_DIR)$(TEST_PROG)$(EXE)
	-$(RUN) $^ $(TEST_PROG_PARAMS)

post_run :
ifeq ($(WF_TARGET),psx)
	testmess
endif

link : $(OBJ_DIR) $(PIGS_LIB) $(LIB_OBJ_DIR)$(TEST_PROG)$(EXE)

.PHONY: test
test : $(LOCAL-PRECONDITIONS) LIBRARY_NAMES_DEFINES link reset_target run_test post_run


#TEST_LIBS += $(PIGSYS) $(MENU) $(PIGS_LIB_DIR)lib$(LIB_NAME).a
TEST_LIBS +=  $(PIGSYS) $(PIGS_LIB_DIR)lib$(LIB_NAME).a $(LIBS)
#TEST_LIBS += $(LIBS)
#TEST_LIBS += $(PIGSYS) $(CPPLIB) $(IFF) $(MATH) $(STREAMS) $(PIGS_OBJ_DIR)/$(LIB_NAME)/lib$(LIB_NAME).a

################################################################################

debug : $(LIB_OBJ_DIR)$(TEST_PROG)$(EXE)
ifeq ($(WF_TARGET),win)
	msdev $^ $(TEST_PROG_PARAMS)
endif
ifeq ($(WF_TARGET),linux)
	$(DEBUGGER) $^ $(TEST_PROG_PARAMS)
endif

################################################################################

$(LIB_OBJ_DIR)$(TEST_PROG)$(EXE) : LIBRARY_NAMES_DEFINES $(LIB_OBJ_DIR)$(TEST_PROG)$(OBJ) $(TEST_OBJS) $(TEST_LIBS)
	@echo ------------------------------------------------------------------------------
	@echo Creating \> \> $@ \< \<
#	@echo ------------------------------------------------------------------------------
ifeq ($(WF_TARGET),linux)
	@echo TEST_LIBS = $(TEST_LIBS)
	@echo ------------------------------------------------------------------------------
	gcc -o $@ $(LIB_OBJ_DIR)$(TEST_PROG)$(OBJ) $(TEST_OBJS) -Xlinker --start-group $(TEST_LIBS) -Xlinker --end-group $(LNARGS) $(SYS_LIBS)
#	The line below doesn't work -- why?
#	link /nologo /out:$(.TARGET) -libpath:"$(MSVCDIR)/lib" /subsystem:$(SUBSYSTEM) /debug /stack:1050624 $^
endif
ifeq ($(WF_TARGET),win)
#	@echo TEST_LIBS = $(TEST_LIBS)
#	@echo ------------------------------------------------------------------------------
	link /nologo /out:$@ -libpath:"$(MSVCDIR)/lib" /subsystem:$(SUBSYSTEM) /debug /stack:1050624 $(LIB_OBJ_DIR)$(TEST_PROG)$(OBJ) $(TEST_OBJS) $(TEST_LIBS)
#	The line below doesn't work -- why?
#	link /nologo /out:$(.TARGET) -libpath:"$(MSVCDIR)/lib" /subsystem:$(SUBSYSTEM) /debug /stack:1050624 $^
endif
ifeq  ($(WF_TARGET),psx)
	@echo $(TEST_LIBS)
	$(PSX_DIR)/bin/psylink -g -wm -m -c -n 1024 @<<
;
; Linker control file for psx version
;
	org     $$80010000
	;
	; Library files
	;

text    group                   ; Group containing defined data
bss     group   bss             ; Group containing uninitialized data

	;
	; These sections are created by the C compiler.  Specifying them
	; here is not strictly necessary but does ensure that they appear
	; in the correct order in the linked output file.
	;
	section .rdata,text
	section .text,text
	section .data,text
	section .sdata,text

	section .sbss,bss       ; The bss sections
	section .bss,bss

	; The following line initializes the program counter register so
	; that the downloader sets the entry point before the program
	; is executed.  SN_ENTRY_POINT is defined in a module in
	; ligsn.lib and clears the bss, sets up the heap, etc., before
	; calling main().

	regs    pc=__SN_ENTRY_POINT

	INCLUDE $(LIB_OBJ_DIR)$(TEST_PROG)$(OBJ)

	%foreach Lib $(TEST_LIBS)
		INCLIB $(Lib)
	%end
	<< $(LINKPOST)
	move /q $(LIB_OBJ_DIR)$(EXE) $(PIGS_LIB_DIR)
endif
