################################################################################
# Makefile for version library
################################################################################
# 'make all'            : Builds the version library
# 'make test'           : Builds a test application which exercises the library
# 'make clean'          : Deletes all of the results of this Makefile
################################################################################

.MS_NMAKE

LIB_NAME = version
TEST_PROG = test

################################################################################

LIB_OBJS += \

################################################################################

!include ../Makefile.lib
