#=============================================================================
# Makefile for ini library
#=============================================================================
# 'make all'            : Builds the ini library.
# 'make test'           : Builds a test application which exercises the ini library.
# 'make clean'		: Deletes all of the results of this makefile.
#=============================================================================

LIB_NAME = ini
include ../../GNUMakefile.env
#TEST_LIBS += $(MATH) $(STREAMS) $(CPPLIB) $(MEMORY) $(HAL)

LIB_OBJS += \
	$(LIB_OBJ_DIR)profile$(OBJ) \

#include ../GNUMakefile.lib
include ../../GNUMakefile.rul

################################################################################
