#=============================================================================
# Makefile for ini library
#=============================================================================
# 'make all'            : Builds the ini library.
# 'make test'           : Builds a test application which exercises the ini library.
# 'make clean'		: Deletes all of the results of this makefile.
#=============================================================================

.MS_NMAKE

LIB_NAME = ini
!include ../../Makefile.env
#TEST_LIBS += $(MATH) $(STREAMS) $(CPPLIB) $(MEMORY) $(HAL)

LIB_OBJS += \
	$(LIB_OBJ_DIR)profile.obj \

!include ../Makefile.lib

################################################################################
