#=============================================================================
# Makefile for cdda library
#=============================================================================
# 'make all'		: Builds the iff library.
# 'make test'		: Builds a test application which exercises the iff library.
# 'make clean'		: Deletes all of the results of this makefile.
#=============================================================================

.MS_NMAKE

LIB_NAME = cdda
!include ../../Makefile.env

################################################################################

LIB_OBJS += \
	$(LIB_OBJ_DIR)cd.obj \

################################################################################

!include ../Makefile.lib

################################################################################
