//=============================================================================
// gteflags.h:
//=============================================================================
//=============================================================================
// kts gte flag definitions

#define GTE_FLAGB_LIME_OUTOFRANGE  12
#define GTE_FLAGB_LIMD2_OUTOFRANGE  13
#define GTE_FLAGB_LIMD1_OUTOFRANGE  14
#define GTE_FLAGB_TEST4_UNDERFLOW  15
#define GTE_FLAGB_TEST4_OVERFLOW  16
#define GTE_FLAGB_DIVIDE_OVERFLOW  17
#define GTE_FLAGB_LIMC_OUTOFRANGE  18
#define GTE_FLAGB_LIMB3_OUTOFRANGE  19
#define GTE_FLAGB_LIMB2_OUTOFRANGE  20
#define GTE_FLAGB_LIMB1_OUTOFRANGE  21
#define GTE_FLAGB_LIMA3_OUTOFRANGE  22
#define GTE_FLAGB_LIMA2_OUTOFRANGE  23
#define GTE_FLAGB_LIMA1_OUTOFRANGE  24
#define GTE_FLAGB_TEST3_UNDERFLOW  25
#define GTE_FLAGB_TEST3_OVERFLOW  26
#define GTE_FLAGB_TEST2_UNDERFLOW  27
#define GTE_FLAGB_TEST2_OVERFLOW  28
#define GTE_FLAGB_TEST1_UNDERFLOW 29
#define GTE_FLAGB_TEST1_OVERFLOW 30
#define GTE_FLAGB_SUM 31

#define GTE_FLAGF_LIME_OUTOFRANGE     (1<<GTE_FLAGB_LIME_OUTOFRANGE)
#define GTE_FLAGF_LIMD2_OUTOFRANGE    (1<<GTE_FLAGB_LIMD2_OUTOFRANGE)
#define GTE_FLAGF_LIMD1_OUTOFRANGE    (1<<GTE_FLAGB_LIMD1_OUTOFRANGE)
#define GTE_FLAGF_TEST4_UNDERFLOW     (1<<GTE_FLAGB_TEST4_UNDERFLOW)
#define GTE_FLAGF_TEST4_OVERFLOW      (1<<GTE_FLAGB_TEST4_OVERFLOW)
#define GTE_FLAGF_DIVIDE_OVERFLOW     (1<<GTE_FLAGB_DIVIDE_OVERFLOW)
#define GTE_FLAGF_LIMC_OUTOFRANGE     (1<<GTE_FLAGB_LIMC_OUTOFRANGE)
#define GTE_FLAGF_LIMB3_OUTOFRANGE    (1<<GTE_FLAGB_LIMB3_OUTOFRANGE)
#define GTE_FLAGF_LIMB2_OUTOFRANGE    (1<<GTE_FLAGB_LIMB2_OUTOFRANGE)
#define GTE_FLAGF_LIMB1_OUTOFRANGE    (1<<GTE_FLAGB_LIMB1_OUTOFRANGE)
#define GTE_FLAGF_LIMA3_OUTOFRANGE    (1<<GTE_FLAGB_LIMA3_OUTOFRANGE)
#define GTE_FLAGF_LIMA2_OUTOFRANGE    (1<<GTE_FLAGB_LIMA2_OUTOFRANGE)
#define GTE_FLAGF_LIMA1_OUTOFRANGE    (1<<GTE_FLAGB_LIMA1_OUTOFRANGE)
#define GTE_FLAGF_TEST3_UNDERFLOW     (1<<GTE_FLAGB_TEST3_UNDERFLOW)
#define GTE_FLAGF_TEST3_OVERFLOW      (1<<GTE_FLAGB_TEST3_OVERFLOW)
#define GTE_FLAGF_TEST2_UNDERFLOW     (1<<GTE_FLAGB_TEST2_UNDERFLOW)
#define GTE_FLAGF_TEST2_OVERFLOW      (1<<GTE_FLAGB_TEST2_OVERFLOW)
#define GTE_FLAGF_TEST1_UNDERFLOW     (1<<GTE_FLAGB_TEST1_UNDERFLOW)
#define GTE_FLAGF_TEST1_OVERFLOW      (1<<GTE_FLAGB_TEST1_OVERFLOW)
#define GTE_FLAGF_SUM                 (1<<GTE_FLAGB_SUM)

//=============================================================================
