#=============================================================================
# GNUmakefile for iff library
#=============================================================================
# 'make all'		: Builds the iff library.
# 'make test'		: Builds a test application which exercises the iff library.
# 'make clean'		: Deletes all of the results of this makefile.
#=============================================================================

LIB_NAME = input
include ../../GNUMakefile.env
TEST_PROG = inputtest

################################################################################

LIB_OBJS += \
	$(LIB_OBJ_DIR)inputdig$(OBJ) \

################################################################################

#include ../GNUMakefile.lib
include ../../GNUMakefile.rul

################################################################################
