#==============================================================================
## script to build makefile.levels
# By Kevin T. Seghetti Copyright (c) 2001 World Foundry Group
#==============================================================================

$nLevel = 0;

while ( <STDIN> )
{
	chop;
	if ( $_ )
	{
		@levels[$nLevel] = $_;
		++$nLevel;
	}
}

print "# makefile.levels : generated by makefile.levels.pl DO NOT MODIFY\n\n";
print "LEVELS = \\\n";

$nLevel = 0;
while($nLevel < @levels)
{
		print "\t@levels[$nLevel]\\\n";
		++$nLevel;
}	

print "\n\n";

print "ALL : ALLLEVELS\n\n";


print "ALLLEVELS .MISER :\n\t\%foreach Dir \$(LEVELS)\n";
print "\t\t@%echo ===============================================================================\n";
print "\t\t@%echo Building \$(Dir)\n";
print "\t\t@%echo -------------------------------------------------------------------------------\n";
print "\t\t%chdir \$(Dir)\n";
print "\t\t..\\buildlvl.bat\n";
print "\t\tmake \$(Dir)\n";
print "\t\t%chdir \$(MAKEDIR)\n";
print "\t\t%end\n";
print "\n";


print "clean .MISER :\n";
print "	\%foreach Dir \$(LEVELS)\n";
print "\t\t@%echo -------------------------------------------------------------------------------\n";
print "\t\t@%echo \$(Dir)\n";
print "\t\t-( cd \$(Dir) ; make /nologo \$(MFLAGS) \$(.TARGET) )\n";
print "	\%end\n";
