#==============================================================================
# unixmakefile.levels.pl: script to build makefile.levels
# By Kevin T. Seghetti Copyright (c) 2001 World Foundry Group
#==============================================================================

$nLevel = 0;

while ( <STDIN> )
{
	chop;
	if ( $_ )
	{
		@levels[$nLevel] = $_;
		++$nLevel;
	}
}

print "# makefile.levels : generated by makefile.levels.pl DO NOT MODIFY\n\n";
print "LEVELS = \\\n";

$nLevel = 0;
while($nLevel < @levels)
{
		print "\t@levels[$nLevel]\\\n";
		++$nLevel;
}	

print "\n\n";

print "ALL : LEVELMAKEFILES ALLLEVELS\n\n";

print ".PHONY : LEVELMAKEFILES\n";
print "LEVELMAKEFILES : ";
$nLevel = 0;
while($nLevel < @levels)
{
		print " @levels[$nLevel]/Makefile";
		++$nLevel;
}	
print "\n\n";


$nLevel = 0;
while($nLevel < @levels)
{
		print "@levels[$nLevel]/Makefile :\n";
        print "\tcd @levels[$nLevel] ; ../buildlvl ; cd ..\n\n"; 
		++$nLevel;
}	



print "build_level = cd \$(dir) ; make \$(dir); cd .. ;\n";
print ".PHONY : ALLLEVELS\n";
print "ALLLEVELS : \n";
print "\t\$(foreach dir, \$(LEVELS), \$(build_level) )\n";



# print "ALLLEVELS :\n\t\%foreach Dir \$(LEVELS)\n";
# print "\t\t@%echo ===============================================================================\n";
# print "\t\t@%echo Building \$(Dir)\n";
# print "\t\t@%echo -------------------------------------------------------------------------------\n";
# print "\t\t%chdir \$(Dir)\n";
# print "\t\t..\\buildlvl.bat\n";
# print "\t\tmake \$(Dir)\n";
# print "\t\t%chdir \$(MAKEDIR)\n";
# print "\t\t%end\n";
# print "\n";


print "clean_level = cd \$(dir) ; make clean ; cd .. ;\n";
print ".PHONY : clean\n";
print "clean : \n";
print "\t\$(foreach dir, \$(LEVELS), \$(clean_level) )\n";

#
# print "clean  :\n";
# print " \%foreach Dir \$(LEVELS)\n";
# print "\t\t@%echo -------------------------------------------------------------------------------\n";
# print "\t\t@%echo \$(Dir)\n";
# print "\t\t-( cd \$(Dir) ; make /nologo \$(MFLAGS) \$(.TARGET) )\n";
# print " \%end\n";
