//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by toolbar.rc
//
#define IDD_COLORCLIP_PANEL             101
#define IDC_SAVE                        101
#define IDC_RUN                         101
#define IDD_COLORCLIP_FLOATER           102
#define IDC_LOAD                        102
#define IDC_MAKE                        102
#define IDC_EXPORT_OBJECT               102
#define IDD_ASCIIOUT_PANEL              103
#define IDC_MAKE_LEVEL                  103
#define IDD_UTILTEST_PANEL              104
#define IDC_RUN_LEVEL                   104
#define IDD_APPDATA_PANEL               105
#define IDB_BROWSE                      105
#define IDC_LINT_LEVEL                  105
#define IDD_CLASSNAME                   106
#define IDC_CLEAN_LEVEL                 106
#define IDD_HDUMP                       107
#define IDC_ATTRIBUTES                  107
#define IDD_COLOUR                      108
#define IDD_TARGETPLATFORM              108
#define IDD_PARAMETERS                  109
#define IDD_COMMAND_LINE_PARAMETERS     109
#define IDD_BUILD                       110
#define IDD_DEBUG_STREAMS               111
#define IDD_TOOLBAR_BUTTONS             112
#define IDC_COLORCLIP_NEWFLOAT          1000
#define IDC_ASCIIOUT_PICK               1002
#define IDC_TESTER_MAKEOBJECT           1003
#define IDC_TESTER_MAKEGROUP            1004
#define IDC_APPDATA_EDIT                1004
#define IDC_TESTER_GROUPOBJS            1005
#define IDC_APPDATA_GET                 1005
#define IDC_TESTER_OPENGROUP            1006
#define IDC_APPDATA_PUT                 1006
#define IDC_TESTER_CLOSEGROUP           1007
#define IDC_TESTER_EXPLODEGROUP         1008
#define IDC_TESTER_UNGROUP              1009
#define IDC_TESTER_SAVETOFILE           1010
#define IDC_TESTER_LOADFROMFILE         1011
#define IDC_TESTER_SETENV               1012
#define IDC_TESTER_SETWAV               1013
#define IDS_TESTER_ANIMON               1014
#define IDS_TESTER_ANIMOFF              1015
#define IDS_TESTER_RENDER               1016
#define IDC_BUTTON1                     1017
#define IDC_CHECK1                      1018
#define IDC_PARANOID                    1019
#define IDC_RUN_AFTER_MAKE              1020
#define IDC_LIST1                       1021
#define IDC_DEBUG                       1022
#define IDC_RELEASE                     1023
#define IDC_WIN                         1024
#define IDC_PSX                         1025
#define IDC_STREAMTEX                   1026
#define IDC_HD                          1027
#define IDC_WINDOW                      1028
#define IDC_EDIT                        1029
#define IDC_FULLSCREEN                  1029
#define IDC_HEIGHT                      1030
#define IDC_SHOWBOXES                   1031
#define IDC_NOINITIALROTATION           1032
#define IDC_SINGLESIDED                 1033
#define IDC_PERSPECTIVECORRECT          1034
#define IDC_SUBDIVISION                 1035
#define IDC_SHOWPOSITIONS               1037
#define IDC_COLOR_SWATCH1               1039
#define IDC_COLOR_SWATCH2               1040
#define IDC_FRAMERATE                   1040
#define IDC_COLOR_SWATCH3               1041
#define IDC_NO_STREAMS                  1041
#define IDC_COLOR_SWATCH4               1042
#define IDC_HD_STREAMS                  1042
#define IDC_COLOR_SWATCH5               1043
#define IDC_COLOR_SWATCH6               1044
#define IDC_CD_STREAMS                  1044
#define IDC_COLOR_SWATCH7               1045
#define IDC_WARNINGS                    1045
#define IDC_COLOR_SWATCH8               1046
#define IDC_OTHERPARAMS                 1046
#define IDC_COLOR_SWATCH9               1047
#define IDC_ERRORS                      1047
#define IDC_LEVEL_NUMBER                1052
#define IDC_COLOR_SWATCH10              1048
#define IDC_FATAL                       1048
#define IDC_COLOR_SWATCH11              1049
#define IDC_STATISTICS                  1049
#define IDC_COLOR_SWATCH12              1050
#define IDC_PROGRESS                    1050
#define IDC_DEBUGGING                   1051
#define IDC_ACTOR                       1056
#define IDC_MOVEMENT                    1057
#define IDC_COLLISION                   1058
#define IDC_ROOM                        1059
#define IDC_FLOW                        1060
#define IDC_AI                          1061
#define IDC_LEVEL                       1062
#define IDC_LOGO                        1063
#define IDC_TOOL                        1072
#define IDC_CAMERA                      1073
#define IDC_TEXTURE                     1074
#define IDC_MEMORY                      1075
#define IDC_SCRIPT                      1076
#define IDC_ASSETID                     1077
#define IDC_STREAMING                   1078
#define IDC_MAILBOX                     1079
#define IDC_FRAMEINFO                   1080
#define IDC_APPDATA_SLOTSPIN            1202
#define IDC_APPDATA_SLOT                1203
#define IDC_APPDATA_SLOTLABEL           1204
#define IDS_RB_ASCIIOBJECTOUT           30619
#define IDS_RB_ASCIIFILES               30620
#define IDS_RB_SAVEOBJECT               30621
#define IDS_RB_COLORCLIPBOARD           30622
#define IDS_RB_COLORNUM                 30623
#define IDS_RB_APPDATATEST              30624
#define IDS_RB_FILEEXISTS               30625
#define IDC_STATIC                      -1

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        110
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1048
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
