//=============================================================================
// libstrm.inc
//=============================================================================
// included by multiple files, just change this to define more library streams
//=============================================================================
// streamname,default assignment, stream letter, help text

	STREAMENTRY(ccollision,     NULL_STREAM, 'c' ,"Collision system" )

//=============================================================================
