################################################################################
# Makefile for recolib.lib
################################################################################

LIB_NAME = recolib
include ../../GNUMakefile.env
TEST_PROG = recolib
#TEST_LIBS += $(HAL) $(GFX)

################################################################################

LIB_OBJS += \
        $(LIB_OBJ_DIR)hdump$(OBJ) \
        $(LIB_OBJ_DIR)ktstoken$(OBJ) \
        $(LIB_OBJ_DIR)infile$(OBJ) \
        $(LIB_OBJ_DIR)command$(OBJ) \
        $(LIB_OBJ_DIR)fpath$(OBJ) \

################################################################################

#include ../GNUMakefile.lib
include ../../GNUMakefile.rul

################################################################################
