//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Prim.rc
//
#define IDD_SPHEREPARAM                 101
#define IDD_SPHEREPARAM2                101
#define IDB_SPINNER                     102
#define IDD_CYLINDERPARAM               102
#define IDD_CYLINDERPARAM2              102
#define IDC_SPINNERCUR                  103
#define IDD_BOXPARAM                    103
#define IDD_BOXPARAM2                   103
#define IDD_WAVEPARAM                   104
#define IDD_SCAMERA                     105
#define IDD_SCAMERAPARAM                105
#define IDD_LIGHT_PARAM                 106
#define IDD_CYLINDERPARAM1              107
#define IDD_DIRLIGHTPARAM               108
#define IDD_DUMMY1                      109
#define IDD_DUMMY2                      110
#define IDD_DUMMY3                      111
#define IDD_DUMMY4                      112
#define IDD_SPHEREPARAM1                113
#define IDD_DUMMY5                      114
#define IDD_DUMMY6                      115
#define IDD_FSPOTLIGHTPARAM             116
#define IDD_SPOTLIGHT                   116
#define IDD_SPLINEPARAM                 117
#define IDD_SPLINEPARAM1                117
#define IDD_NGONPARAM2                  118
#define IDD_NGONPARAM1                  119
#define IDD_DONUTPARAM2                 120
#define IDD_DONUTPARAM1                 121
#define IDD_SAMPLEPARAM                 122
#define IDD_FCAMERAPARAM                123
#define IDD_PATCHGRIDPARAM              124
#define IDD_TRIPATCHPARAM               125
#define IDD_PSPHEREPARAM1               126
#define IDD_PSPHEREPARAM2               127
#define IDD_TORUSPARAM1                 128
#define IDB_HYBRIDKEYBUTTONS            128
#define IDD_TORUSPARAM2                 129
#define IDB_MASK_HYBRIDKEYBUTTONS       129
#define IDD_MORPHPARAM                  130
#define IDD_MORPHPARAM2                 130
#define IDD_MORPHPARAM1                 131
#define IDD_FREE_SPOTLIGHT              132
#define IDD_LIGHT_SHADOW                134
#define IDD_RECTANGLEPARAM              135
#define IDD_BOOLPARAM1                  136
#define IDD_BOOLPARAM2                  137
#define IDD_TAPEHELPER                  138
#define IDD_SPHEREPARAM3                139
#define IDD_CYLINDERPARAM3              140
#define IDD_TORUSPARAM3                 141
#define IDD_TUBEPARAM1                  142
#define IDD_TUBEPARAM2                  143
#define IDD_TUBEPARAM3                  144
#define IDD_BOXPARAM1                   145
#define IDD_BOXPARAM3                   146
#define IDD_CONEPARAM1                  147
#define IDD_CONEPARAM2                  148
#define IDD_CONEPARAM3                  149
#define IDD_HEDRAPARAM                  150
#define IDD_HELIXPARAM1                 151
#define IDD_HELIXPARAM2                 152
#define IDB_TEXT_BUTTONS                152
#define IDD_DONUTPARAM3                 153
#define IDB_TEXT_MASKBUTTONS            153
#define IDD_NGONPARAM3                  154
#define IDD_HELIXPARAM3                 156
#define IDC_CROSS_HAIR                  156
#define IDD_RECTANGLEPARAM3             157
#define IDD_RECTANGLEPARAM2             158
#define IDD_RECTANGLEPARAM1             159
#define IDD_CIRCLEPARAM2                160
#define IDD_CIRCLEPARAM1                161
#define IDD_ELLIPSEPARAM3               162
#define IDD_ELLIPSEPARAM2               163
#define IDD_ELLIPSEPARAM1               164
#define IDD_CIRCLEPARAM3                165
#define IDD_ARCPARAM3                   166
#define IDD_ARCPARAM2                   167
#define IDD_ARCPARAM1                   168
#define IDD_RAINPARAM                   169
#define IDD_STARPARAM2                  170
#define IDD_STARPARAM1                  171
#define IDD_SNOWPARAM                   172
#define IDD_TEXTPARAM                   173
#define IDD_INTERPPARAMS                174
#define IDD_SPLINEPARAM2                175
#define IDD_TEAPOTPARAM1                176
#define IDD_TEAPOTPARAM2                177
#define IDD_TEAPOTPARAM3                178
#define IDD_CUBICMORPH_KEYINFO          179
#define IDD_BOXPARAM2_BAK               180
#define IDC_RADIUS                      1000
#define IDC_SEGMENTS                    1001
#define IDC_AMPLITUDE                   1001
#define IDC_PARAM_P                     1001
#define IDC_TI_ARCFROM                  1001
#define IDC_CREATEDIAMETER              1002
#define IDC_CYCLES                      1002
#define IDC_HEMISPHERE                  1002
#define IDC_CAPSEGMENTS                 1002
#define IDC_PARAM_Q                     1002
#define IDC_TI_ARCTO                    1002
#define IDC_CREATERADIUS                1003
#define IDC_PHASE                       1003
#define IDC_SCALE_P                     1003
#define IDC_SEGSPINNER                  1004
#define IDC_NUMNODES                    1004
#define IDC_SCALE_Q                     1004
#define IDC_RADSPINNER                  1005
#define IDC_CAPSEGSPINNER               1005
#define IDC_OBSMOOTH                    1006
#define IDC_AMPSPINNER                  1006
#define IDC_PARAM_PSPIN                 1006
#define IDC_TI_ARCFROMSPINNER           1006
#define IDC_LENGTH                      1007
#define IDC_CYCSPINNER                  1007
#define IDC_HEMISPHERESPINNER           1007
#define IDC_PARAM_QSPIN                 1007
#define IDC_TI_ARCTOSPINNER             1007
#define IDC_LENSPINNER                  1008
#define IDC_PHSSPINNER                  1008
#define IDC_SCALE_PSPIN                 1008
#define IDC_SIDES                       1009
#define IDC_NUMSPINNER                  1009
#define IDC_SCALE_QSPIN                 1009
#define IDC_POINTS                      1009
#define IDC_SIDESPINNER                 1010
#define IDC_HEIGHT                      1010
#define IDC_HEIGHTEDIT                  1010
#define IDC_SCALE_R                     1010
#define IDC_POINTSSPINNER               1010
#define IDC_WIDTHSPINNER                1011
#define IDC_PIESLICESPIN1               1011
#define IDC_SCALE_RSPIN                 1011
#define IDC_DISTORTSPINNER              1011
#define IDC_HEIGHTSPINNER               1012
#define IDC_PIESLICESPIN2               1012
#define IDC_DISTORT                     1012
#define IDC_BROWSE                      1013
#define IDC_HSEGSPIN                    1013
#define IDC_RADSPINNER2                 1013
#define IDC_CAPSEGSPIN                  1013
#define IDC_OBJFILENAME                 1014
#define IDC_HSEGS                       1014
#define IDC_FOV                         1015
#define IDC_WSEGSPIN                    1015
#define IDC_FOVSPINNER                  1016
#define IDC_WSEGS                       1016
#define IDC_LRED                        1017
#define IDC_LSEGSPIN                    1017
#define IDC_FOVSPINNER2                 1017
#define IDC_LREDSPINNER                 1018
#define IDC_LSEGS                       1018
#define IDC_FOV2                        1018
#define IDC_SHOWCAMCONE                 1019
#define IDC_CHECK1                      1020
#define IDC_SHOW_CONE                   1020
#define IDC_BOOL_OPTIMIZE               1020
#define IDC_SHOWHORZLINE                1020
#define IDC_SPEC_LEN                    1020
#define IDC_HEMI_RECENTER               1020
#define IDC_SLICEON                     1020
#define IDC_ARCPIE                      1020
#define IDC_HIDE_EMITTER                1020
#define IDC_LGREEN                      1021
#define IDC_BUTTON1                     1021
#define IDC_CREATE_MORPHKEY             1021
#define IDC_15MM                        1021
#define IDC_SCALE_RESET                 1021
#define IDC_LGREENSPINNER               1022
#define IDC_BUTTON2                     1022
#define IDC_PROJ_IMAGE                  1022
#define IDC_20MM                        1022
#define IDC_LBLUE                       1023
#define IDC_RADIO1                      1023
#define IDC_BUTTON3                     1023
#define IDC_TARG_REFERENCE              1023
#define IDC_RECT_LIGHT                  1023
#define IDC_24MM                        1023
#define IDC_BOOL_UNION                  1023
#define IDC_HEMI_SQUASH                 1023
#define IDC_SMOOTH_ALL                  1023
#define IDC_FAM_TETRA                   1023
#define IDC_HELIX_CW                    1023
#define IDC_PARTICLE_DOTS               1023
#define IDC_PART_BOTH                   1023
#define IDC_LBLUESPINNER                1024
#define IDC_RADIO2                      1024
#define IDC_BUTTON4                     1024
#define IDC_TARG_COPY                   1024
#define IDC_CIRCLE_LIGHT                1024
#define IDC_28MM                        1024
#define IDC_BOOL_INTERSECTION           1024
#define IDC_HEMI_CHOP                   1024
#define IDC_SMOOTH_SIDES                1024
#define IDC_FAM_OCTA                    1024
#define IDC_HELIX_CCW                   1024
#define IDC_PARTICLE_TICKS              1024
#define IDC_PART_BODY                   1024
#define IDC_RADIO3                      1025
#define IDC_BUTTON5                     1025
#define IDC_LHOTSIZESPINNER             1025
#define IDC_TARG_MOVE                   1025
#define IDC_35MM                        1025
#define IDC_MAP_RANGE                   1025
#define IDC_BOOL_DIFFERENCEA            1025
#define IDC_SMOOTH_NONE                 1025
#define IDC_FAM_DODEC                   1025
#define IDC_PART_LID                    1025
#define IDC_BOOL_DIFFERENCEAB           1025
#define IDC_RADIO4                      1026
#define IDC_BUTTON6                     1026
#define IDC_LHOTSIZE                    1026
#define IDC_TARG_INSTANCE               1026
#define IDC_50MM                        1026
#define IDC_BOOL_DISPRESULT             1026
#define IDC_FAM_STAR1                   1026
#define IDC_BUTTON7                     1027
#define IDC_LFALLOFFSPINNER             1027
#define IDC_85MM                        1027
#define IDC_BOOL_DIFFERENCEB            1027
#define IDC_BOOL_DIFFERENCEBA           1027
#define IDC_CHECK2                      1028
#define IDC_BUTTON8                     1028
#define IDC_LFALLOFF                    1028
#define IDC_135MM                       1028
#define IDC_TICKMARKS                   1028
#define IDC_BOOL_SHOWHIDDENOPS          1028
#define IDC_GENTEXTURE                  1028
#define IDC_PARTICLE_CONSTANTRATE       1028
#define IDC_BUTTON9                     1029
#define IDC_LTDISTSPINNER               1029
#define IDC_200MM                       1029
#define IDC_BUTTON10                    1030
#define IDC_LASPECT_SPIN                1030
#define IDC_BUTTON11                    1031
#define IDC_LASPECT                     1031
#define IDC_LIST1                       1032
#define IDC_MORPHTARG_LIST              1032
#define IDC_LBLUR_SPIN                  1032
#define IDC_BOOL_OPERANDS               1032
#define IDC_SCROLLBAR2                  1033
#define IDC_LBLUR                       1033
#define IDC_KEYTIME                     1033
#define IDC_KEYTIMESPIN                 1034
#define IDC_SCROLLBAR1                  1035
#define IDC_SCROLLBAR3                  1035
#define IDC_TCB_T                       1035
#define IDC_SCROLLBAR4                  1036
#define IDC_TCB_TSPIN                   1036
#define IDC_EDIT1                       1037
#define IDC_TEXTENTRY                   1037
#define IDC_TCB_C                       1037
#define IDC_TCB_CSPIN                   1038
#define IDC_USER1                       1039
#define IDC_PICK_MORPHTARG              1039
#define IDC_LIGHT_COLOR                 1039
#define IDC_TCB_B                       1039
#define IDC_ICORNER                     1040
#define IDC_TCB_BSPIN                   1040
#define IDC_ISMOOTH                     1041
#define IDC_DCORNER                     1042
#define IDC_OBCIRCULAR                  1042
#define IDC_DSMOOTH                     1043
#define IDC_RADIUS1                     1043
#define IDC_DBEZIER                     1044
#define IDC_RAD1SPINNER                 1044
#define IDC_RADIUS2                     1045
#define IDC_RAD2SPINNER                 1046
#define IDC_TORUS_ROT                   1047
#define IDC_TURNS                       1047
#define IDC_TORUS_ROTSPIN               1048
#define IDC_TORUS_TWIST                 1049
#define IDC_TURNSSPINNER                1049
#define IDC_SHOW_RANGES                 1050
#define IDC_TORUS_TWISTSPIN             1050
#define IDC_TURNSEDIT                   1050
#define IDC_BIASSPINNER                 1051
#define IDC_BIASEDIT                    1052
#define IDC_USE_ATTEN                   1062
#define IDC_START_RANGE_SPIN            1063
#define IDC_START_RANGE                 1064
#define IDC_END_RANGE_SPIN              1065
#define IDC_END_RANGE                   1066
#define IDC_LMULTSPINNER                1067
#define IDC_LMULT                       1068
#define IDC_LTDIST                      1069
#define IDC_SSTEPSSPINNER               1069
#define IDC_TDIST                       1070
#define IDC_SHAPESTEPS                  1070
#define IDC_TDISTSPINNER                1071
#define IDC_HITHER_SPIN                 1072
#define IDC_LVSPINNER                   1073
#define IDC_HITHER                      1073
#define IDC_LV                          1074
#define IDC_YON_SPIN                    1074
#define IDC_LSSPINNER                   1075
#define IDC_YON                         1075
#define IDC_LS                          1076
#define IDC_LHSPINNER                   1077
#define IDC_LH                          1078
#define IDC_OVERSHOOT                   1080
#define IDC_PROJECTOR                   1081
#define IDC_BITMAP_FIT                  1082
#define IDC_LIGHT_ON                    1083
#define IDC_PREVKEY                     1090
#define IDC_NEXTKEY                     1091
#define IDC_KEYNUM                      1092
#define IDC_TARGNAME                    1157
#define IDC_TCB_GRAPH                   1179
#define IDC_ADAPTIVE                    1225
#define IDC_OPTIMIZE                    1500
#define IDC_LENS                        3000
#define IDC_LENSSPINNER                 3001
#define IDC_MAP_BIAS                    3002
#define IDC_MAP_BIAS_SPIN               3003
#define IDC_MAP_SIZE                    3004
#define IDC_MAP_SIZE_SPIN               3005
#define IDC_RT_BIAS                     3006
#define IDC_RT_BIAS_SPIN                3007
#define IDC_LENGTHEDIT                  3009
#define IDC_WIDTHEDIT                   3010
#define IDC_PICK_BOOLOPERAND            3011
#define IDC_BOOL_RECALC                 3012
#define IDC_BOOL_DISPOPS                3015
#define IDC_BOOL_UPDATERENDER           3016
#define IDC_BOOL_UPDATEMANUAL           3017
#define IDC_BOOL_UPDATEALWAYS           3018
#define IDC_BOOL_UPDATESELECT           3019
#define IDC_TI_POSX                     3019
#define IDC_TI_POSXSPIN                 3020
#define IDC_TI_POSY                     3021
#define IDC_TI_POSYSPIN                 3022
#define IDC_TI_CREATE                   3023
#define IDC_TI_POSZ                     3024
#define IDC_PIESLICE1                   3024
#define IDC_TEXTITALIC                  3024
#define IDC_TI_POSZSPIN                 3025
#define IDC_PIESLICE2                   3025
#define IDC_TEXTUNDERLINE               3025
#define IDC_TI_CLOSE                    3026
#define IDC_RADSPINNER1                 3027
#define IDC_TI_FINISH                   3027
#define IDC_CREATECUBE                  3028
#define IDC_CREATEBOX                   3029
#define IDC_FAM_STAR2                   3030
#define IDC_VERT_BASIC                  3031
#define IDC_VERT_CENTER                 3032
#define IDC_VERT_SIDES                  3033
#define IDC_RADIUSSPIN                  3034
#define IDC_MANUAL_CLIP                 3035
#define IDC_CREATEEDGE                  3036
#define IDC_VPT_PARTICLES               3036
#define IDC_CREATECENTER                3037
#define IDC_VPT_PARTICLESSPIN           3037
#define IDC_ARCFROM                     3038
#define IDC_PARTICLE_SIZE               3038
#define IDC_ARCFROMSPINNER              3039
#define IDC_PARTICLE_SIZESPIN           3039
#define IDC_ARCTO                       3040
#define IDC_PARTICLE_START              3040
#define IDC_ARCTOSPINNER                3041
#define IDC_PARTICLE_STARTSPIN          3041
#define IDC_CREATE_EEC                  3042
#define IDC_PARTICLE_LIFE               3042
#define IDC_TEXTFONT                    3042
#define IDC_CREATE_CEE                  3043
#define IDC_PARTICLE_LIFESPIN           3043
#define IDC_TEXTSIZEEDIT                3043
#define IDC_EMITTER_WIDTH               3044
#define IDC_TEXTSIZESPINNER             3044
#define IDC_EMITTER_WIDTHSPIN           3045
#define IDC_TEXTBOLD                    3045
#define IDC_EMITTER_HEIGHT              3046
#define IDC_EMITTER_HEIGHTSPIN          3047
#define IDC_PARTICLE_SPEED              3048
#define IDC_PARTICLE_SPEEDSPIN          3049
#define IDC_PARTICLE_VARIATION          3050
#define IDC_PARTICLE_VARIATIONSPIN      3051
#define IDC_PARTICLE_CUST               3052
#define IDC_TEXTEXAMPLE                 3053
#define IDC_PARTICLE_BIRTHRATE          3053
#define IDC_PARTICLE_BIRTHRATESPIN      3054
#define IDC_PARTICLE_MAXRATE            3055
#define IDC_NO_CROSSOVER                3056
#define IDC_PARTICLE_TUMBLE             3056
#define IDC_RND_PARTICLES               3056
#define IDC_FAR_RANGE                   3057
#define IDC_PARTICLE_TUMBLESPIN         3057
#define IDC_RND_PARTICLESSPIN           3057
#define IDC_FAR_RANGE_SPIN              3058
#define IDC_PARTICLE_SCALE              3058
#define IDC_NEAR_RANGE                  3059
#define IDC_PARTICLE_SCALESPIN          3059
#define IDC_NEAR_RANGE_SPIN             3060
#define IDC_REND_PARTICLES              3060
#define IDC_TI_ADDPOINT                 3061
#define IDC_REND_PARTICLESSPIN          3061
#define IDC_MAP_RANGE_SPIN              3062
#define IDC_GLOBAL_SET                  3063
#define IDC_CAST_SHADOWS                3064
#define IDC_ABS_MAP_BIAS                3065
#define IDC_SHADOW_MAPS                 3066
#define IDC_RAY_TRACED_SHADOWS          3067
#define IDC_EXCLUDE_DLG                 3069
#define IDC_PROJ_MAPNAME                3070
#define IDC_PARTICLE_REND1              3071
#define IDC_TEAPART                     3071
#define IDC_PARTICLE_REND2              3072
#define IDC_PARTICLE_REND3              3073
#define ID_STATIC                       3073
#define IDC_TEA_BODY                    3074
#define IDC_TEA_HANDLE                  3075
#define IDC_TEA_SPOUT                   3076
#define IDC_TEA_LID                     3077
#define IDS_DS_CREATE                   10008
#define IDS_DB_FREE                     10009
#define IDS_DB_BONES                    10010
#define IDS_DB_BASIC                    10011
#define IDS_DB_RING_ARRAY               10012
#define IDS_DB_SLAVECONTROL             10013
#define IDS_DB_SLAVE_CONTROL            10014
#define IDS_DB_TAPEHELPER               10015
#define IDS_DS_RINGARRAYPAR             10037
#define IDS_DS_RADIUS                   10038
#define IDS_DS_CYCLES                   10039
#define IDS_DS_AMPLITUDE                10040
#define IDS_DS_PHASE                    10041
#define IDS_DS_EXCLUDE__                10122
#define IDS_DS_INCLUDE__                10123
#define IDS_DS_LIGHTCOL                 10175
#define IDS_DB_TDIST                    20072
#define IDS_DB_MULTIPLIER               20315
#define IDS_DB_ATTENSTART               20316
#define IDS_DB_ATTENEND                 20317
#define IDS_DB_HOTSIZE                  20318
#define IDS_DB_FALLSIZE                 20319
#define IDS_DB_COLOR                    20320
#define IDS_DB_ASPECT_RATIO             20323
#define IDS_DB_TAPE_LENGTH              20326
#define IDS_DB_NRANGE                   20453
#define IDS_DB_FRANGE                   20454
#define IDS_RB_OBJECT                   30004
#define IDS_RB_PARAMETERS               30028
#define IDS_RB_ANGLE                    30029
#define IDS_RB_AMOUNT                   30031
#define IDS_RB_LENGTH                   30038
#define IDS_RB_WIDTH                    30039
#define IDS_RB_HEIGHT                   30040
#define IDS_RB_WSEGS                    30041
#define IDS_RB_HSEGS                    30042
#define IDS_RB_LSEGS                    30043
#define IDS_RB_FOV                      30044
#define IDS_RB_RADIUS                   30045
#define IDS_RB_SEGS                     30046
#define IDS_RB_SIDES                    30047
#define IDS_RB_SMOOTH                   30048
#define IDS_RB_RED                      30049
#define IDS_RB_GREEN                    30050
#define IDS_RB_BLUE                     30051
#define IDS_RB_HOTSIZE                  30052
#define IDS_RB_TRANSFORM                30053
#define IDS_RB_BASEPARAMS               30054
#define IDS_DB_TARGET                   30055
#define IDS_DB_DOT_TARGET               30056
#define IDS_DB_OMNI                     30057
#define IDS_DB_TARGET_SPOT              30058
#define IDS_DB_DIRECTIONAL              30059
#define IDS_DB_FREE_SPOT                30060
#define IDS_DB_NONE                     30061
#define IDS_RB_OBJ_MOD                  30062
#define IDS_RB_WORLD_MOD                30063
#define IDS_DB_GENERAL_PARAMS           30064
#define IDS_DB_DIR_PARAMS               30065
#define IDS_DB_SPOT_PARAMS              30066
#define IDS_DB_SHADOW_PARAMS            30067
#define IDS_DB_SELECT_TO_FIT            30068
#define IDS_DB_OMNI_LIGHT               30069
#define IDS_DB_DIR_LIGHT                30070
#define IDS_DB_DIRECT                   30071
#define IDS_DB_FSPOT                    30072
#define IDS_DB_SPOT                     30073
#define IDS_DB_LIGHT                    30074
#define IDS_DB_TAPE                     30075
#define IDS_DB_GENERAL                  30076
#define IDS_RB_EDITKEYINFO              30128
#define IDS_RB_GEOMETERIC               30157
#define IDS_RB_SHAPES                   30158
#define IDS_RB_LIGHTS                   30159
#define IDS_RB_CAMERAS                  30160
#define IDS_RB_HELPERS                  30161
#define IDS_RB_SPACEWARPS               30162
#define IDS_RB_SYSTEMS                  30163
#define IDS_DB_CAMERA                   30164
#define IDS_DB_SIMPLECAM                30165
#define IDS_RB_PICKOPERAND              30263
#define IDS_RB_PRIMITIVES               30264
#define IDS_RB_BOOLEAN                  30475
#define IDS_RB_COMPOUNDOBJECTS          30476
#define IDS_RB_INVALIDBOOLEAN           30477
#define IDS_RB_OPERANDS                 30478
#define IDS_RB_PICKBOOLEAN              30479
#define IDS_RB_OPERANDA                 30480
#define IDS_RB_OPERANDATRANSFORM        30481
#define IDS_RB_OPERANDB                 30482
#define IDS_RB_OPERANDBTRANSFORM        30483
#define IDS_RB_OPERAND                  30484
#define IDS_RB_CUBICMORPHCONTROL        30485
#define IDS_RB_TARGETNUMBER             30486
#define IDS_RB_MORPH                    30487
#define IDS_RB_MORPHOBJECT              30488
#define IDS_RB_PICKTARGETS              30489
#define IDS_RB_CURRENTTARGETS           30490
#define IDS_RB_SPRAY                    30491
#define IDS_RB_SNOW                     30492
#define IDS_RB_PARTICLESYSTEMS          30493
#define IDS_RB_VIEWPARTICLES            30494
#define IDS_RB_DROPSIZE                 30495
#define IDS_RB_SPEED                    30496
#define IDS_RB_VARIATION                30497
#define IDS_RB_STARTTIME                30498
#define IDS_RB_LIFETIME                 30499
#define IDS_RB_BIRTHRATE                30500
#define IDS_RB_TUMBLE                   30501
#define IDS_RB_TUMBLERATE               30502
#define IDS_RB_SPHERE                   30503
#define IDS_RB_CREATIONMETHOD           30504
#define IDS_RB_KEYBOARDENTRY            30505
#define IDS_RB_HEMISPHERE               30506
#define IDS_RB_BOX                      30507
#define IDS_RB_CYLINDER                 30508
#define IDS_RB_CIRCLESEGMENTS           30509
#define IDS_RB_CAPSEGMENTS              30510
#define IDS_RB_SLICEON                  30511
#define IDS_RB_SLICEFROM                30512
#define IDS_RB_SLICETO                  30513
#define IDS_RB_GENTEXCOORDS             30514
#define IDS_RB_CONE                     30515
#define IDS_RB_RADIUS1                  30516
#define IDS_RB_RADIUS2                  30517
#define IDS_RB_TEAPOT                   30518
#define IDS_DB_TARGET_CAM               30519
#define IDS_RB_TORUS                    30520
#define IDS_RB_ROTATION2                30521
#define IDS_RB_TWIST                    30522
#define IDS_RB_HEDRA                    30523
#define IDS_RB_FAMILY                   30524
#define IDS_RB_PVALUE                   30525
#define IDS_RB_QVALUE                   30526
#define IDS_RB_PSCALE                   30527
#define IDS_RB_QSCALE                   30528
#define IDS_RB_RSCALE                   30529
#define IDS_RB_TUBE                     30530
#define IDS_RB_SEGMENTS                 30531
#define IDS_DB_FREE_CAM                 30532
#define IDS_RB_SPHERE2                  30543
#define IDS_RB_CREATIONMETHOD2          30544
#define IDS_RB_FROM                     30545
#define IDS_RB_TO                       30546
#define IDS_RB_KEYBOARDENTRY2           30547
#define IDS_RB_HEMISPHERE2              30548
#define IDS_RB_BOX2                     30549
#define IDS_RB_CYLINDER2                30550
#define IDS_RB_CIRCLESEGMENTS2          30551
#define IDS_RB_CREATIONMETHOD3          30552
#define IDS_RB_KEYBOARDENTRY3           30553
#define IDS_RB_CIRCLESEGMENTS3          30554
#define IDS_RB_CREATIONMETHOD4          30555
#define IDS_RB_BODY                     30633
#define IDS_RB_LID                      30634
#define IDS_RB_SPOUT                    30635
#define IDS_RB_HANDLE                   30636
#define IDS_RB_HEIGHTSEGS               30639
#define IDS_RB_MAPSIZE                  30640
#define IDS_RB_MAPBIAS                  30641
#define IDS_RB_MAPRANGE                 30642
#define IDS_RB_RAYBIAS                  30643
#define IDS_RB_NEARPLANE                30644
#define IDS_RB_FARPLANE                 30645
#define IDS_RB_PICKMORPHTARGET          30657
#define IDS_RB_CREATEMORPHKEY           30658
#define IDS_RB_BOOLEANABORTED           30661
#define IDS_RB_BOOLEACOMPLETED          30662
#define IDS_RB_FLAKESIZE                30676
#define IDS_TH_RADIUS                   40033
#define IDS_TH_CIRCULAR                 40034
#define IDS_TH_SIDES                    40035
#define IDS_TH_RADIUS1                  40036
#define IDS_TH_RADIUS2                  40037
#define IDS_TH_PARAMETERS               40038
#define IDS_TH_LINE                     40079
#define IDS_TH_FROM                     40161
#define IDS_TH_TO                       40162
#define IDS_TH_DISTORTION               40163
#define IDS_TH_STARPOINTS               40164
#define IDS_TH_TURNS                    40165
#define IDS_TH_BIAS                     40166
#define IDS_TH_NEEDTWOSPLINEPOINTS      40188
#define IDS_TH_ERRORTWOCONSECUTIVE      40189
#define IDS_TH_NGON                     40259
#define IDS_TH_SPLINES                  40260
#define IDS_TH_CREATION_METHOD          40261
#define IDS_TH_KEYBOARD_ENTRY           40262
#define IDS_TH_TRI_PATCH                40263
#define IDS_TH_PATCH_GRIDS              40264
#define IDS_TH_ARC                      40265
#define IDS_TH_CIRCLE                   40266
#define IDS_TH_RECTANGLE                40267
#define IDS_TH_STAR                     40268
#define IDS_TH_DONUT                    40269
#define IDS_TH_TEXT                     40270
#define IDS_TH_HELIX                    40271
#define IDS_TH_ELLIPSE                  40272
#define IDS_TH_QUAD_PATCH               40273
#define IDS_TH_MAX_TEXT                 40274
#define IDS_TH_SIZE                     40275
#define IDS_TH_INTERPOLATION            40276
#define IDS_TH_HEIGHT                   40278
#define IDS_TH_DIRECTION                40280
#define IDS_TH_ARIAL                    40281
#define IDS_TH_QUADPATCH                40282
#define IDS_TH_QUADPATCHOBJECT          40283
#define IDS_TH_TRIPATCH                 40284
#define IDS_TH_TRIPATCHOBJECT           40285
#define IDS_TH_SIMPSPLINE               40315
#define IDS_DS_PARAMCHG                 40316
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        157
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         3074
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
