@*============================================================================
@* FlagBloc.inc: oas data for generic object flags
@*============================================================================

@ifndef(DEFAULT_TEMPLATE)(@define DEFAULT_TEMPLATE 0)

	PROPERTY_SHEET_HEADER(Flags)
	TYPEENTRYBOOLEAN(Template Object,,DEFAULT_TEMPLATE)
	PROPERTY_SHEET_FOOTER

@*============================================================================
