@*============================================================================
@* toolset.inc: oas data for tool ownership
@*============================================================================

	PROPERTY_SHEET_HEADER(Toolset)
	TYPEENTRYOBJREFERENCE(Tool A,Tool)
	TYPEENTRYOBJREFERENCE(Tool B,Tool)
	TYPEENTRYOBJREFERENCE(Tool C,Tool)
	TYPEENTRYOBJREFERENCE(Tool D,Tool)
	TYPEENTRYOBJREFERENCE(Tool E,Tool)
	TYPEENTRYOBJREFERENCE(Tool F,Tool)
	PROPERTY_SHEET_FOOTER
	LEVELCONFLAGENDCOMMON

@*============================================================================

