//=============================================================================
// libstrm.inc
//=============================================================================
// included by multiple files, just change this to define more library streams
//=============================================================================
// streamname,default assignment, stream letter, help text

	STREAMENTRY(croom,	NULL_STREAM, 'r' ,"Room system output" )
	STREAMENTRY(croomslots,	NULL_STREAM, 'R' ,"Room Slot Assets system" )

//=============================================================================
