################################################################################
# makefile for registry library
################################################################################
# 'make all'            : Builds the registry library
# 'make test'		: Builds a test application which exercises the library
# 'make clean'		: Deletes all of the results of this Makefile
################################################################################

.MS_NMAKE

LIB_NAME = registry
!include ../../Makefile.env

################################################################################

LIB_OBJS += \
        $(LIB_OBJ_DIR)$(LIB_NAME).obj \


################################################################################

!include ../Makefile.lib

################################################################################
