#=============================================================================
# Makefile for menu library
#=============================================================================
# 'make all'		: Builds the iff library.
# 'make test'		: Builds a test application which exercises the iff library.
# 'make clean'		: Deletes all of the results of this makefile.
#=============================================================================

LIB_NAME = menu
include ../../GNUMakefile.env
#TEST_PROG = test
TEST_LIBS += $(PIGSYS)

################################################################################

#        $(LIB_OBJ_DIR)simpmenu$(OBJ) \

LIB_OBJS += \
       $(LIB_OBJ_DIR)menu$(OBJ) \

################################################################################

#include ../GNUMakefile.lib
include ../../GNUMakefile.rul

################################################################################
